### ISSUE TITLE
Add Linux support

### ISSUE THREAD

**Issue by grillbaer** [grillbaer/spectracle#10]
- Test on Linux
- Installer from jpackage

**Comment by grillbaer** [comment]
Debian package build for linux amd64 works, but still needs some refinement: deb package attributes, better target dir instead of /opt to add it to path. Not yet really tested, but at least the windows shows up.

**Comment by grillbaer** [comment]
- Missing unicode symbols fixed with dependency to ttf-ancient-fonts. Works, but symbols look a little ancient ;-)
- Target dir is now /usr, so Spectracle is in path
- Fixed non-working icon, ok now
- Exposure control flips image to all white when going < 0 ... hm

**Comment by telethonic** [comment]
Very cool software, many thanks :-)

I tried to create an RPM under Fedora 39 (editing `pom.xml` to have `<type>RPM</type>`, and with `rpm-build` installed), but still getting some errors there.

In the meantime, it runs fine from the JAR files from `spectracle-app/target/jmods`. I attached the command I used to run it.

As a reference for others, what was installed to enable the build and run:

`java-17-openjdk, java-17-openjdk-headless, java-17-openjdk-devel, maven-openjdk17`

[run_spectracle_command.txt](https://github.com/user-attachments/files/17355666/run_spectracle_command.txt)
